### ISSUE TITLE
Broken frame issue

### ISSUE THREAD

**Issue by naghmesara** [Textalk/websocket-php#128]
Hi

how to fix broken frame in client?
i am get bellow ConnectionException in script log file:
`Broken frame, read 0 of stated 2 bytes.`

Regards

**Comment by sirn-se** [comment]
The error imply that the client expects there is data to read on the stream, but there isn't. Possibly due to the underlying connection being closed or having time out.
There are two parallell answers to this.

1) This can happen. You're code need to catch and handle situations where connections unexpectedly drop.

2) If you believe this to be a bug in this repo, we need more information about the issue. Please provide as much as possible of the following;
* How this error can be reproduced
* A log of the data flow around the time the issue appears
* The full exception text, including meta state

**Comment by BrooksYang** [comment]
Got the same issue, here is my environment:
1. Laravel Framework 8.39.0
2. textalk/websocket: "^1.5"

log: Broken frame, read 0 of stated 2 bytes.

**Comment by BrooksYang** [comment]
@sirn-se

**Comment by jeeinn** [comment]
Me too
That should be the https://github.com/Textalk/websocket-php/pull/140
