### ISSUE TITLE
Looping receive() is not working

### ISSUE THREAD

**Issue by shakirwebdev** [Textalk/websocket-php#178]
Hi, I have this project to listen to a client. Once response is working fine, but when I want to continously receive the response. It broke on localhost. returning timeout error. here is some of my code

```
public function __invoke()
    {
        $booking_id = 'some-booking-id';
        $membe_id = 'some-member-id';

        $client = new Client("wss://foo.bar/v1/websockets/GetHttp?booking_id=".$booking_id."&member_id=".$membe_id, [
            'headers' => [ // Additional headers, used to specify subprotocol
                'Connection' => 'Upgrade',
                'Upgrade' => 'websocket',
                'Sec-WebSocket-Version' => 13,
                'Sec-WebSocket-Extensions' => 'permessage-deflate; client_max_window_bits'
            ],
            'return_obj' => true, // Return Message instance rather than just text
            'timeout' => 30, // 1 minute time out
        ]);

        while (true) {
            try {
                $message = $client->receive();
                echo $message;
                // Act on received message
                // Break while loop to stop listening
            } catch (\WebSocket\ConnectionException $e) {
                dd($e);
                // Possibly log errors
            }
        }
        $client->close();
    }
```

**Comment by sirn-se** [comment]
The `receive()` method will wait for input during timeout seconds. But if there's nothing to read within that period, the underlying connection will close, causing a timeout exception. This is expected behaviour of stream I/O, it prevents sockets being kept open forever when not explicitly closed by the application using them.

The timeout error should be considered a recoverable error. Calling `receive()` again _should_ reconnect the client.

**Comment by shakirwebdev** [comment]
My bad, its showing 504 Gateaway timeout from nginx. Do I have to set the context here? Btw I'm still testing on localhost.

**Comment by shakirwebdev** [comment]
As for now I only need client side to retrieve data, I'll just use vue this time.
