### ISSUE TITLE
Unable to send and receive messages

### ISSUE THREAD

**Issue by kadnan** [Textalk/websocket-php#31]
I am using `Rachet` Library to create a WebSocket Server. I am connecting that server as:

```
use WebSocket\Client;
$client_wa = new Client("ws://localhost:9000");
$client_wa->send("Hello WebSocket.org!");
print_r($client_wa);
```

At server end I am not getting message neither I am getting message from server. Issue is not with Server as my web client works fine. My server logic is given as:

```
public function onMessage(ConnectionInterface $from, $msg) {
        $numRecv = count($this->clients) - 1;
        print "WA got the message:- ".$msg;
        echo sprintf('Connection %d sending message "%s" to %d other connection%s' . "\n"
            , $from->resourceId, $msg, $numRecv, $numRecv == 1 ? '' : 's');

        foreach ($this->clients as $client) {
            if ($from === $client) {
                $msg = 'WA Server responds:- '.$msg;
                $client->send($msg);
            }
        }
    }
```

It does connect as it does indicate when the client dies.

**Comment by fiddur** [comment]
Does the autotests work for you?  There is one test that makes a ratchett-server and tests against.

What PHP version(s) are you using?  The autotests only run on 5.4 and 5.5 on travis…

**Comment by sinasalek** [comment]
It seems there is a compatibility issues with Rachet or it may be a generic problem.
I was experiencing the same problem and it was caused by an endless loop. The problem was after connecting to the socket server, the client waits for reading the whole response, but it's no the way to do it, at least not in this case since Rachet only return the header on connection.
I found a similar issue on Rachet issue queue + the patch that fixed the problem.

https://github.com/Textalk/websocket-php/issues/19
https://github.com/Textalk/websocket-php/commit/686d367fc61ec363b0070d6f92e59d2a77b23ba7

**Comment by Enelar** [comment]
@kadnan i suppose this issue were solved?

**Comment by sinasalek** [comment]
Yes

**Comment by zanechua** [comment]
This throws up an error for me too. PHP 7.1
