### ISSUE TITLE
Bad $payload after PING

### ISSUE THREAD

**Issue by VadikV** [Textalk/websocket-php#98]
Need add: 
$payload = ''; 
after line:
https://github.com/Textalk/websocket-php/blob/ab022415da9e090ae12cd2d027ed1fe31f258c42/lib/Base.php#L238

**Comment by sirn-se** [comment]
In what way is it "bad"? As far as I can tell, the receiveFragment() method returns received value as expected.

**Comment by VadikV** [comment]
After "ping" garbage remains in variable $payload, which is returned from the function

**Comment by sirn-se** [comment]
As the repo is built, that's the expected behavior. The calling code need to check the opcode when handling returns from the receive() method.

However, we _do_ have an issue when a control message is received between the parts of a fragmented message. That's not easily fixed in existing methods. My plan is to introduce a listener method instead, as the preferred way of receiving messages.

**Comment by sirn-se** [comment]
Version `1.4.1` changes this behavior and don't return ping or pong messages from `receive()` method.
